sonar.projectKey=equpo-s-team_equpo-backend
sonar.organization=equpo-s-team

sonar.sources=src
sonar.tests=test
sonar.exclusions=**/node_modules/**,**/dist/**,test/**
sonar.test.inclusions=test/**/*.test.js

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.coverage.exclusions=\
  src/domains/*/handlers/**,\
  src/domains/*/firestore/**,\
  src/domains/room/realtimeServer.ts,\
  src/domains/ai/**,\
  src/domains/quotes/**,\
  src/app.ts,\
  src/index.ts,\
  src/db.ts,\
  src/auth.ts,\
  src/systemAuth.ts,\
  src/config.ts,\
  src/firebaseAdmin.ts,\
  src/utils/redisClient.ts

sonar.sourceEncoding=UTF-8
